version: '3.1'
services:
  statistic-service:
    image: modmoto/w3champions-ui:dev-17
    container_name: w3champions-ui
    restart: always
    environment:
      - VIRTUAL_HOST=blood-bowl-league.com
      - BASE_URL=https://statistic-service.blood-bowl-league.com/

networks:
  default:
    external:
      name: nginx-proxy
