version: '3.1'
services:
  statistic-service:
    image: modmoto/w3champions-statistic-service:latest
    container_name: w3champions-statistic-service-ngi
    restart: always
    environment:
      - VIRTUAL_HOST=statistic-service.blood-bowl-league.com

networks:
  default:
    external:
      name: nginx-proxy
